import fs from "node:fs/promises";
import path from "node:path";
import { ensureRuntime, runtimePaths } from "./runtime.js";
import { listFilesRecursive, readTextSafe, writeText } from "../utils/fs.js";

const INJECT_SNIPPET = "<!-- OpenVila Widget -->\n<script src=\"/openvila/widget.js\" defer></script>";

function widgetHtmlTemplate() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>OpenVila Widget Preview</title>
  <style>
    body {
      margin: 0;
      font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
      background: linear-gradient(135deg, #f3f7ff, #f0fff9);
      min-height: 100vh;
      display: grid;
      place-items: center;
      color: #0f172a;
    }
    .card {
      width: min(90vw, 800px);
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 16px;
      padding: 20px;
      box-shadow: 0 20px 60px rgba(15, 23, 42, 0.08);
    }
    h1 { margin: 0 0 8px; font-size: 24px; }
    p { margin: 0 0 16px; color: #475569; }
    iframe {
      width: 100%;
      height: 540px;
      border: 1px solid #dbeafe;
      border-radius: 12px;
      background: #f8fafc;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>OpenVila Widget Preview</h1>
    <p>This preview file was generated by <code>/install</code>.</p>
    <iframe srcdoc="<div style='font-family:sans-serif;padding:20px'><h2>Embed Example</h2><p>Inject <code>&lt;script src=\"/openvila/widget.js\" defer&gt;&lt;/script&gt;</code> before <code>&lt;/body&gt;</code>.</p></div>"></iframe>
  </div>
</body>
</html>
`;
}

function widgetScriptTemplate() {
  return `(function () {
  if (document.getElementById("openvila-launcher")) return;

  var panel = document.createElement("div");
  panel.id = "openvila-panel";
  panel.style.position = "fixed";
  panel.style.right = "20px";
  panel.style.bottom = "84px";
  panel.style.width = "360px";
  panel.style.maxWidth = "calc(100vw - 24px)";
  panel.style.height = "520px";
  panel.style.background = "#ffffff";
  panel.style.border = "1px solid #dbeafe";
  panel.style.borderRadius = "14px";
  panel.style.boxShadow = "0 24px 64px rgba(15, 23, 42, 0.2)";
  panel.style.display = "none";
  panel.style.overflow = "hidden";
  panel.style.zIndex = "2147483647";

  panel.innerHTML = "" +
    '<div style=\"padding:10px 12px;border-bottom:1px solid #e2e8f0;background:#f8fafc;font:600 14px/1.4 sans-serif\">OpenVila</div>' +
    '<div id=\"openvila-messages\" style=\"height:400px;overflow:auto;padding:12px;font:14px/1.5 sans-serif;background:#ffffff\"></div>' +
    '<form id=\"openvila-form\" style=\"display:flex;gap:8px;padding:10px;border-top:1px solid #e2e8f0;background:#f8fafc\">' +
      '<input id=\"openvila-input\" placeholder=\"Ask anything...\" style=\"flex:1;padding:8px;border:1px solid #cbd5e1;border-radius:8px\" />' +
      '<button style=\"padding:8px 12px;border:none;border-radius:8px;background:#2563eb;color:#fff;cursor:pointer\">Send</button>' +
    '</form>';

  var button = document.createElement("button");
  button.id = "openvila-launcher";
  button.textContent = "V";
  button.style.position = "fixed";
  button.style.right = "20px";
  button.style.bottom = "20px";
  button.style.width = "52px";
  button.style.height = "52px";
  button.style.borderRadius = "50%";
  button.style.border = "none";
  button.style.background = "linear-gradient(135deg,#2563eb,#0ea5e9)";
  button.style.color = "#fff";
  button.style.font = "700 20px/1 sans-serif";
  button.style.cursor = "pointer";
  button.style.zIndex = "2147483647";
  button.style.boxShadow = "0 12px 28px rgba(37,99,235,.4)";

  function append(role, text) {
    var list = document.getElementById("openvila-messages");
    if (!list) return;
    var item = document.createElement("div");
    item.style.marginBottom = "10px";
    item.innerHTML = '<div style="font-size:12px;color:#64748b">' + role + '</div>' +
      '<div style="background:#f8fafc;border:1px solid #e2e8f0;padding:8px;border-radius:8px;white-space:pre-wrap">' + text + '</div>';
    list.appendChild(item);
    list.scrollTop = list.scrollHeight;
  }

  button.addEventListener("click", function () {
    panel.style.display = panel.style.display === "none" ? "block" : "none";
  });

  panel.querySelector("#openvila-form").addEventListener("submit", async function (e) {
    e.preventDefault();
    var input = panel.querySelector("#openvila-input");
    var text = (input.value || "").trim();
    if (!text) return;
    input.value = "";
    append("You", text);

    try {
      var res = await fetch("/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: text })
      });
      var data = await res.json();
      append("Vila", data.answer || data.error || "No response");
    } catch (err) {
      append("Vila", "Request failed: " + err.message);
    }
  });

  document.body.appendChild(panel);
  document.body.appendChild(button);
})();
`;
}

async function injectSnippetToFile(targetPath) {
  const raw = await readTextSafe(targetPath);
  if (!raw) {
    return false;
  }
  if (raw.includes("openvila/widget.js")) {
    return false;
  }

  let next;
  if (raw.includes("</body>")) {
    next = raw.replace("</body>", `${INJECT_SNIPPET}\n</body>`);
  } else {
    next = `${raw}\n${INJECT_SNIPPET}\n`;
  }

  await fs.writeFile(targetPath, next, "utf8");
  return true;
}

async function findHtmlCandidates(cwd) {
  const files = await listFilesRecursive(cwd, {
    maxFiles: 400,
    onlyExt: [".html", ".htm"],
  });

  return files.sort((a, b) => {
    const score = (p) => {
      const rel = path.relative(cwd, p).toLowerCase();
      if (rel.startsWith("templates/")) return 0;
      if (rel.includes("index")) return 1;
      return 5;
    };
    return score(a) - score(b);
  });
}

async function attachRunScript(cwd) {
  const packagePath = path.join(cwd, "package.json");
  const raw = await readTextSafe(packagePath);
  if (!raw) {
    return { changed: false, reason: "package.json not found" };
  }

  let pkg;
  try {
    pkg = JSON.parse(raw);
  } catch {
    return { changed: false, reason: "package.json parse failed" };
  }

  pkg.scripts = pkg.scripts || {};
  if (!pkg.scripts["openvila:run"]) {
    pkg.scripts["openvila:run"] = "openvila run";
  }

  await fs.writeFile(packagePath, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
  return { changed: true };
}

export async function installWidget(cwd, options = {}) {
  const paths = await ensureRuntime(cwd);
  await writeText(paths.widget, widgetHtmlTemplate());
  await writeText(paths.widgetScript, widgetScriptTemplate());

  const result = {
    preview: paths.widget,
    script: paths.widgetScript,
    injected: [],
    snippet: INJECT_SNIPPET,
    startup: null,
  };

  if (options.apply) {
    const candidates = await findHtmlCandidates(cwd);
    const targets = options.all ? candidates : candidates.slice(0, 1);

    for (const target of targets) {
      const changed = await injectSnippetToFile(target);
      if (changed) {
        result.injected.push(path.relative(cwd, target));
      }
    }
  }

  if (options.attachStart) {
    result.startup = await attachRunScript(cwd);
  }

  return result;
}
